import "../assets/css/How.css";

function How() {
  return (
    <section className="room-two" id="how-it-works">
      <div className="container">

        {/* SECTION TITLE */}
        <div className="sec-title text-center sec-title--two">
          <h3 className="sec-title__title">How It Works ?</h3>
          <br />
          <h5 className="sec-title__subtitle">
           A Simple, Structured Path from Fractional Investment to Returns
          </h5>
        </div>

        {/* GRID */}
        <div className="room-two__grid">

          {/* ITEM 1 */}
          <div
            className="icons-box style-3 wow animate__animated animate__zoomIn"
            data-wow-duration="1.5s"
            data-wow-delay="0s"
          >
            <div className="tf-icon">
              <i className="fa-solid fa-magnifying-glass"></i>
            </div>
            <div className="content">
              <h5 className="title">Discover Opportunities</h5>
              <p className="text-1">
               Explore carefully vetted real estate investments with clear insights and exit
plans.
              </p>
            </div>
          </div>

          {/* ITEM 2 */}
          <div
            className="icons-box style-3 wow animate__animated animate__zoomIn"
            data-wow-duration="1.5s"
            data-wow-delay="0.2s"
          >
            <div className="tf-icon">
              <i className="fa-solid fa-shield-halved"></i>
            </div>
            <div className="content">
              <h5 className="title">Invest Securely</h5>
              <p className="text-1">
               Complete a secure digital investment process with transparent ownership.
              </p>
            </div>
          </div>

          {/* ITEM 3 */}
          <div
            className="icons-box style-3 wow animate__animated animate__zoomIn"
            data-wow-duration="1.5s"
            data-wow-delay="0.4s"
          >
            <div className="tf-icon">
              <i className="fa-solid fa-chart-line"></i>
            </div>
            <div className="content">
              <h5 className="title">Receive Distributions</h5>
              <p className="text-1">
               Earn stable rental income generated by the asset during the holding period.
              </p>
            </div>
          </div>

          {/* ITEM 4 */}
          <div
            className="icons-box style-3 wow animate__animated animate__zoomIn"
            data-wow-duration="1.5s"
            data-wow-delay="0.6s"
          >
            <div className="tf-icon">
              <i className="fa-solid fa-arrow-right-arrow-left"></i>
            </div>
            <div className="content">
              <h5 className="title">Planned Exit</h5>
              <p className="text-1">
                At the planned exit stage, the asset is sold and profits are distributed.
              </p>
            </div>
          </div>

        </div>
      </div>
    </section>
  );
}

export default How;
